### ISSUE TITLE
Define the CONNECTED status and maybe provide proxy to get status in readable format.

### ISSUE THREAD

**Issue by flacohenao** [plcpeople/nodeS7#100]
@gfcittolin 

Right now, we have ths defined status:

![image](https://user-images.githubusercontent.com/10132006/80618143-9147e180-8a08-11ea-8990-320285c416d5.png)

would be nice if you guys declare the 4 (READY) status in the source code, and maybe.. if you think is usefull (I think it is) provide a method to return the status not exposing the control property 

> conn._connectionState

but exposing a getter instead of be able to actually set a value through that property like:

> .getConnectionStatus()

that returns the "String version" of the states!

Maybe the 4 status is just for internal use?? and not need to be exposed?

if not, we can close the issue.

**Comment by gfcittolin** [comment]
I think what you mean by "READY" would be the `CONN_CONNECTED` state, right? If not, what would be the difference between them?

Note that there's already a getter called `isConnected`, so you could for example test it for `true` before trying to call other methods (or listening to the `connect` and `disconnect` events)

**Comment by flacohenao** [comment]
Ok, nice!

I haven't seen the `isConnected` getter. didn't dive on source that much I gues...
