### ISSUE TITLE
Prevents parser errors from crashing the process

### ISSUE THREAD

**Issue by gfcittolin** [plcpeople/nodeS7#108]
As seen on #107, parser errors can cause the whole process to crash, as the code path is being triggered by an incoming network packet. Such errors should be handled as stream `error` events instead

**Comment by flacohenao** [comment]
I think it is actually happen... did you test you laste commit?

**Comment by gfcittolin** [comment]
Did the very bad thing to do a change after testing. My bad :facepalm: 
Fixed on c25286d4fc25290c686ab92919a2377b99dcb0aa
