### ISSUE TITLE
force output to activate a relay

### ISSUE THREAD

**Issue by frankville** [plcpeople/nodeS7#119]
Hi, first of all thanks for this library. It's a great tool.

I'm new to PLC integration, and I'm trying to activate a relay connected to one of the outputs (Q0.0 ) by writing a bit to that memory position like this:

 conn.writeItem(["Out0"],[true], ...) where Out0 is a variable with value "Q0.0,X0.0" 

Is it possible to achieve this? I've also tried to write directly to the physical output by putting "Q0.0:P,X0.0" and many other variants of this but the result is that I can see this variable active when reading the values but it does not activate the relay.

**Comment by plcpeople** [comment]
Q0.0 would be the correct item syntax for writing to the output directly.
