### ISSUE TITLE
Address conversion

### ISSUE THREAD

**Issue by plurimediatech** [plcpeople/nodeS7#128]
Hello,

I'm working with a client who installed a new Siemens Simotion machine. We previously developed an interactive web-based dashboard to manage his Siemens 1500 machine. The new machine uses a completely different address format and I'm not sure if and how a conversion is possible: 

New Format: 10-01-00-01-00-67-84-00-04-80
Old Format: DB51.DBX100.1

Attached the "conversion diagram" given with the technical specs, the same for both machines.

![image](https://user-images.githubusercontent.com/114089311/191538343-2097d924-2cb9-415b-94eb-2e6faedab1e9.png)

Thank you in advance for any advice.

**Comment by plcpeople** [comment]
The address can be converted fairly easily:
First byte is 10h always
Second 01 = data type = bool
Third, fourth 0001 = Repetition factor = 1 in this case (Array of only 1 so a single item)
DB number is 67 hex = 103 decimal
Memory area 84 = Data Block (DB)
The last 3 bytes can be considered together as a bit offset, or divided by 8 to get a byte offset, in this case 480 hex =1152 dec = 144 when divided by 8 to convert to a byte offset.

So for your example, you could use DB103.DBX144.0 which would be a bit in the data block in the format you are used to.

Attached is a screenshot of the various relevant data types from the S7 help on the "any pointer":
![image](https://user-images.githubusercontent.com/8019526/192656166-32077fdc-ded2-4482-8872-f29bbeb0c959.png)

And the memory areas:
![image](https://user-images.githubusercontent.com/8019526/192656239-fa2cd769-dc8a-4a1e-aa23-0841d60e292a.png)
