### ISSUE TITLE
Question: MPI over Serial

### ISSUE THREAD

**Issue by ptorrent** [plcpeople/nodeS7#141]
Hello there !

Just a question about this module. Does it support serial communication over RS485 ? Or Do I've to use a "convertor" for make it works ? 

Thanks for your support !

**Comment by plcpeople** [comment]
It only works with a purpose-built MPI to S7-Ethernet converter like the Helmholz Netlink PRO series, IBHNet S7++, etc.  It doesn't do direct serial with or without the "PC Adapter" and won't work with a standard RS485 to Ethernet device.
