### ISSUE TITLE
How do you know the packet content?

### ISSUE THREAD

**Issue by EasonWang01** [plcpeople/nodeS7#16]
```

	self.connectReq = new Buffer([0x03, 0x00, 0x00, 0x16, 0x11, 0xe0, 0x00, 0x00, 0x00, 0x02, 0x00, 0xc0, 0x01, 0x0a, 0xc1, 0x02, 0x01, 0x00, 0xc2, 0x02, 0x01, 0x02]);
	self.negotiatePDU = new Buffer([0x03, 0x00, 0x00, 0x19, 0x02, 0xf0, 0x80, 0x32, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0xf0, 0x00, 0x00, 0x08, 0x00, 0x08, 0x03, 0xc0]);
	self.readReqHeader = new Buffer([0x03, 0x00, 0x00, 0x1f, 0x02, 0xf0, 0x80, 0x32, 0x01, 0x00, 0x00, 0x08, 0x00, 0x00, 0x0e, 0x00, 0x00, 0x04, 0x01]);
	self.readReq = new Buffer(1500);
	self.writeReqHeader = new Buffer([0x03, 0x00, 0x00, 0x1f, 0x02, 0xf0, 0x80, 0x32, 0x01, 0x00, 0x00, 0x08, 0x00, 0x00, 0x0e, 0x00, 0x00, 0x05, 0x01]);
	self.writeReq = new Buffer(1500);
```

Is there a datasheet or it just the profinet protocal?

**Comment by plcpeople** [comment]
PROFINET is different - this is the "S7 Protocol" and as far as I know Siemens has not made the protocol details available to the public.  However, you can look at the packets from any HMI/OPC software to the PLC with Wireshark and the S7comm plug-in and it gives a pretty good description of each byte in the packet.  The buffers in the code are just a "starting point" and most of the bytes are overwritten as the packets are prepared for sending.  You can also Google the S7 protocol and "RFC1006" for more information as well.
