### ISSUE TITLE
TypeError: String.toCharCode is not a function

### ISSUE THREAD

**Issue by sembaye** [plcpeople/nodeS7#21]
Found a bug in line 1929:
//theItem.writeBuffer.writeUInt8(String.toCharCode(theItem.writeValue), thePointer);//buggy
theItem.writeBuffer.writeUInt8(theItem.writeValue.charCodeAt(theItem.writeValue), thePointer);

Scenario to reproduce: Write char
conn.writeItems('DB111,CHAR4', 'f', valuesWritten);

Can anyone confirm?

**Comment by plcpeople** [comment]
Yes, I just tested and this is a confirmed bug, thanks.  I will fix, but I believe the following is a more correct fix, as the argument for charCodeAt is the index that you're trying to convert.

theItem.writeBuffer.writeUInt8(theItem.writeValue.charCodeAt(0), thePointer);

I will commit a fix shortly.
