### ISSUE TITLE
Cannot Read DB1,BOOL type on S7 1200

### ISSUE THREAD

**Issue by ouinouin** [plcpeople/nodeS7#51]
Hi, while trying to read BOOL located in a DB, I cannot access to it, 
I tried 
DB1,BOOL0
DB1,BOOL0.0
with no success.
Is this a lack from your implementation, or shall I investigate on PLC/firmware/TIAportal side ?

**Comment by Lichtjaeger** [comment]
Try  `DB1,X0.0`.

**Comment by plcpeople** [comment]
Closing due to no updates in 3 months.  If you are still having issues, please reply with more details.  If the correct addressing is used, DB1 is NOT set up as an optimized data block, and "Enable GET/PUT" is checked in TIA portal, accessing data blocks in an S7-1200 is very well tested.
