### ISSUE TITLE
TCP reconnection.

### ISSUE THREAD

**Issue by sembaye** [plcpeople/nodeS7#6]
Hello,
i try to fix an error in case you pull out the cable off the PLC. At some point during the Error process the ISO CS is 0 and the stack tries to reconnect to the PLC again. Perfect, so far. The an (TCP) timeout occures and nothing happens again. Not good.
In my opinion the stack always has to reconnect. 
There are two options:
1: Try to reconnect from outside
2: The stack handles the TCP-reconnection. I think it should happen in the function/method connectError

@plcpeople : Do you plan to extend the functionality?
If not...@ all: any idea to implement No.1?

I tried to check the connection via isoConnectionState but i thik it would be way easier to change the lib.

**Comment by sembaye** [comment]
If you put following line to the end of connectError the reconnection will be executet:
setTimeout(function(){self.connectNow.apply(self,arguments);}, 1000, self.connectionParams);

I still have the Problem that my callback function that i declared in initiate connection won't start.

**Comment by plcpeople** [comment]
The callback intentionally only runs once on the first connection because
in our application we did not want it called multiple times.  That could be
turned into an option.

I tested TCP reconnection a lot and it always reconnected for me with the
current code but I think that node has changed in the months since I tested
this.  What version of node and what PLC are you using?

**Comment by sembaye** [comment]
I have the latest Version of nodeS7 and i'm using a S7-300.
1. I fixed the TCP reconnection- problem from outside (polling isoConnectionState within an Event emitter), because the Stack doesn't reconnect. I don't exactly know what's the Problem.

2. The option of starting the callback multiple time is in my opinion useful because after an reconnection of the stack nothing happed cause my whole application is running within the callback. 
Question: option means to change the stack itself??
