### ISSUE TITLE
Profinet devices

### ISSUE THREAD

**Issue by lpmwfx** [plcpeople/nodeS7#77]
Can the lib be used for communication with Profinet devices as frequency convertsers and remote IO's like ET200 from Siemens?

**Comment by ceremcem** [comment]
Nearly Impossible AFAIK. Profinet and Profibus are proprietary protocols that requires an extensive reverse engineering effort.

**Comment by lpmwfx** [comment]
Yes I thought so. But is that also true if I use 3rd party devices like a ASI gateway from IFM - They gladly are going to reveal the internal adresses.

**Comment by ceremcem** [comment]
I don't know anything about the mentioned device, but any company can freely produce a proxy device. They can also mimic Profibus/net API for sure, which would give the impression of revealing the Profibus internals.
