### ISSUE TITLE
PROFIBUS DP with CP 5711

### ISSUE THREAD

**Issue by sachinmorabada** [plcpeople/nodeS7#83]
I am using PROFIBUS DP with CP 5711.
How can we communicate and get data?

**Comment by ceremcem** [comment]
https://github.com/plcpeople/nodeS7/issues/77#issuecomment-489634205

**Comment by plcpeople** [comment]
To get data with nodes7 over PROFIBUS there are two requirements:
- #1 The device you are talking to has to support the S7 protocol, which limits you mostly to Siemens PLCs and some VFDs
- #2 You need a converter that converts S7 messages from Ethernet to PROFIBUS.  This has to be something like a IBH or Helmholz Netlink, not a 5711.
